![Numpy logo](images/numpy.png)

# NumPy Tutorials - PART 1: Basics

## 1 Setup

### 1.1 Install library

Check Setup in [README.md][1] for instaling NumPy along with other libraries.

[1]: https://github.com/DheemanthBhat/python-data-science-libraries/blob/main/README.md

### 1.2 Import library

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.1


## 2 Create

### 2.1 One Dimensional Array

Create one dimensional NumPy array.

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

### 2.2 Two Dimensional Array

Create two dimensional NumPy array.

In [3]:
np.array(
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0],
    ]
)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

### 2.3 Multi Dimensional Array

Create three dimensional NumPy array.

In [4]:
np.array(
    [
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 0],
        ],
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 0],
        ],
    ]
)

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]],

       [[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]]])

### 2.4 Range using `arange()`

#### Parameters

NumPy's `arange()` takes three parameters:

1. `start`: Starting value in NumPy array (inclusive).
2. `stop`: Ending value in NumPy array (exclusive).
3. `step`: Step size between two elements.

> **Note**:
> 
> Stop value is exclusive, meaning the stop value is not included in the resulting NumPy array.

#### Examples

##### Example #1

In [5]:
np.arange(start=1, stop=100, step=1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

##### Example #2

In [6]:
np.arange(start=5, stop=6, step=0.1)

array([5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9])

#### Calculate `stop` value

When given the required array length that grows with non default step size of 1, formula for calculating ending value is:

```
stop_value = start_value + (length * step_size)
```

> **Note**:
> 
> Still the stop value is exclusive.

##### Quiz #1

Create an array of length `10` starting from `6` with a step value of `5`

In [7]:
start_val = 6
length = 10
step_size = 5

# Calculate stop value based on length.
stop_val = start_val + (length * step_size)

print("Start value:", start_val)
print("Stop value:", stop_val)

# Generate NumPy array.
np.arange(start=start_val, stop=stop_val, step=step_size)

Start value: 6
Stop value: 56


array([ 6, 11, 16, 21, 26, 31, 36, 41, 46, 51])

## 3 Why NumPy array?

### 3.1 Python `list` vs NumPy array

#### Normal Python list

1. Python lists can store heterogeneous values.
2. Python list is an array of pointers to objects (each object is separately allocated on the heap) hence have higher space complexity compared to NumPy array.
3. Any math operation on Python list takes significantly large amount of time as compared to NumPy array.

In [8]:
start_val = 0
stop_val = 5_000_000

In [9]:
%%timeit

[i**2 for i in range(start_val, stop_val)]

330 ms ± 1.88 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### NumPy array

1. NumPy arrays are **contiguous blocks of memory** with **homogeneous data types**, stored more compactly.

In [10]:
%%timeit

np.arange(start_val, stop_val) ** 2

17.7 ms ± 1.23 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


### 3.2 Python `range` vs NumPy `arange`

NumPy `arange()` supports decimal step value whereas Python `range()` function **does not** support decimal values for step size.

In [11]:
try:
    print(np.arange(0, 5, 0.5).tolist())
    print(list(range(0, 5, 2)))
    print(range(0, 5, 0.5))

except TypeError as err:
    print("Error:", err)

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]
[0, 2, 4]
Error: 'float' object cannot be interpreted as an integer


## 4 Properties of NumPy array

Some important properties of NumPy array can be accessed using:

1. `ndim`: Dimension of NumPy array.
2. `shape`: Shape (rows, columns) of NumPy array.
3. `size`: Size i.e., Total number of elements in all dimensions of NumPy array.
4. `dtype`: Datatype of elements in NumPy array.

Create sample NumPy arrays for testing its properties.

In [12]:
arr_1 = np.array([1, 2, 3, 4, 5])

arr_2 = np.array(
    [
        [1, 2.2, 3.0, 4.0, 5],
        [6.0, 7, 8, 9, 0],
    ]
)

arr_3 = np.array(
    [
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 0],
        ],
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 0],
        ],
    ]
)

#### `ndim`

In [13]:
arr_1.ndim

1

In [14]:
arr_2.ndim

2

In [15]:
arr_3.ndim

3

#### `shape`

In [16]:
arr_1.shape

(5,)

In [17]:
arr_2.shape

(2, 5)

In [18]:
arr_3.shape

(2, 2, 5)

#### `size`

In [19]:
arr_1.size

5

In [20]:
arr_2.size

10

In [21]:
arr_3.size

20

#### `dtype`

In [22]:
arr_1.dtype

dtype('int64')

In [23]:
arr_2.dtype

dtype('float64')

## 5 Datatype

### 5.1 Datatypes

#### Common datatypes

Some commonly used NumPy datatypes:

1. Integer: int8, int16, int32, int64
2. Float: float16, float32, float64
3. Sting: str_, object
4. Boolean: bool

Full list of [NumPy supported datatypes][1].


[1]: https://numpy.org/doc/stable/user/basics.types.html#relationship-between-numpy-data-types-and-c-data-types

In [24]:
np.array([0, 1, 2, 3], dtype=int)

array([0, 1, 2, 3])

In [25]:
np.array([0, 1, 2, 3], dtype=float)

array([0., 1., 2., 3.])

In [26]:
np.array([0, 1, 2, 3], dtype=bool)

array([False,  True,  True,  True])

In [27]:
np.array([0, 1, 2, 3], dtype=str)

array(['0', '1', '2', '3'], dtype='<U1')

### 5.2 Typecasting

#### 1 Automatic type casting

Order of priority in which the automatic type conversion happens:

Priority rule: String > Float > Integer > Boolean

In [28]:
arr = np.array([True, 1])
display(arr)
arr.dtype

array([1, 1])

dtype('int64')

In [29]:
arr = np.array([True, 1, 3.14])
display(arr)
arr.dtype

array([1.  , 1.  , 3.14])

dtype('float64')

In [30]:
arr = np.array([True, 1, 3.14, "A"])
display(arr)
arr.dtype

array(['True', '1', '3.14', 'A'], dtype='<U32')

dtype('<U32')

> **Note**:
> 
> `U` in `<U32` stands for Unicode and 32 represents 32 characters.

#### 2 Using `dtype` property

When datatype is explicitly mentioned using `dtype` the priority rule is not followed.

##### To integer

In [31]:
arr = np.array([False, True, 2], dtype=int)
display(arr)
arr.dtype

array([0, 1, 2])

dtype('int64')

In [32]:
arr = np.array([False, True, 2, 3.14], dtype=int)
display(arr)
arr.dtype

array([0, 1, 2, 3])

dtype('int64')

##### To float

In [33]:
arr = np.array([False, True, 2, 3.14], dtype=float)
display(arr)
arr.dtype

array([0.  , 1.  , 2.  , 3.14])

dtype('float64')

In [34]:
try:
    np.array([False, True, 2, 3.14, "A"], dtype=float)

except ValueError as err:
    print("ValueError:", err)

ValueError: could not convert string to float: 'A'


##### To boolean

In [35]:
arr = np.array([False, True, 0, 2, 3.14, None, "", "A"], dtype=bool)
display(arr)
arr.dtype

array([False,  True, False,  True,  True, False, False,  True])

dtype('bool')

##### To string

In [36]:
np.array([False, True, 2, 3.14, "A"], dtype=str)

array(['False', 'True', '2', '3.14', 'A'], dtype='<U5')

#### 3 Using `astype` function

In [37]:
arr = np.array([1.1, 2.5, 3.9])
display(arr)
arr.dtype

array([1.1, 2.5, 3.9])

dtype('float64')

##### To integer

In [38]:
arr_int = arr.astype(int)  # or np.int16 for smaller size.
display(arr_int)
arr_int.dtype

array([1, 2, 3])

dtype('int64')

##### To boolean

In [39]:
arr_bool = arr.astype(bool)
display(arr_bool)
arr_bool.dtype

array([ True,  True,  True])

dtype('bool')

### 5.3 Object Array

#### dtype `object`

In [40]:
arr = np.array(
    [
        1,
        "Abcd",
        True,
        list([1, 2, 3]),
    ],
    dtype="object",
)
arr

array([1, 'Abcd', True, list([1, 2, 3])], dtype=object)

In [41]:
[type(item) for item in arr]

[int, str, bool, list]

## 6 Accessing elements

> **Note**
>
> Indexing is covered much more elaborately in next notebook: `2_advance.ipynb`.

### 6.1 Indexing

#### Indices Diagram

```python
# -ve indices:  -10   -9   -8   -7   -6   -5   -4   -3   -2   -1
         arr = [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9 ]
# +ve indices:    0    1    2    3    4    5    6    7    8    9
```

##### Syntax

Syntax to access array elements:

```
arr[dim1_idx, dim2_idx, ..., dimn_idx]
```

#### Positive index

In [42]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr[3]

np.int64(3)

In [43]:
arr = np.array(
    [
        [1, 3, 5, 7, 9],
        [2, 4, 6, 8, 0],
    ]
)
arr[1, 2]

np.int64(6)

#### Negative index

In [44]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr[-1]

np.int64(5)

In [45]:
arr = np.array(
    [
        [1, 3, 5, 7, 9],
        [2, 4, 6, 8, 0],
    ]
)
arr[-1, -2]

np.int64(8)

#### Multiple index

In [46]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = [0, -1, 9]

arr[mask]  # arr[[0, -1, 9]]

array([0, 9, 9])

### 6.2 Slicing

#### Indices Diagram

```python
# -ve indices:  -10   -9   -8   -7   -6   -5   -4   -3   -2   -1
         arr = [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9 ]
# +ve indices:    0    1    2    3    4    5    6    7    8    9
```

##### Syntax

```
arr[start_idx : stop_idx : step_value]
```

#### Forward direction

Slicing works in forward direction by default.  
`stop_idx` must always appear after the `start_idx` (as shown in the above indices diagram) when the direction is forward otherwise the slicing returns empty value.

##### Examples

In [47]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr[2:5]

array([2, 3, 4])

In [49]:
arr[5:2]

array([], dtype=int64)

In [50]:
arr[5:-2]

array([5, 6, 7])

Negative index `-2` appears **after** positive index `5` hence three array items were accessible.

In [51]:
arr[5:-7]

array([], dtype=int64)

Negative index `-7` appears **before** positive index `5` hence zero array items were accessible.

#### Reverse direction

Direction is reversed by using negative value as `step_value`.  
`stop_idx` must always appear before the `start_idx` (as shown in the above indices diagram) when the direction is reversed otherwise the slicing returns empty value.

##### Examples

In [52]:
arr[5:2:-1]

array([5, 4, 3])

Index `2` appears **before** index `5`, since the direction is reverse, three array items were accessible.

In [53]:
arr[5:7:-1]

array([], dtype=int64)

Index `7` appears **after** index `5`, since the direction is reverse, zero array items were accessible.

In [54]:
arr[5:-7:-1]

array([5, 4])

Negative index `-7` appears **before** positive index `5`, since the direction is reverse,  two array items were accessible.

#### Usecase

##### Example #1

In [55]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Fetch even numbers:

In [56]:
arr[::2]

array([0, 2, 4, 6, 8])

Fetch odd numbers:

In [57]:
arr[1::2]

array([1, 3, 5, 7, 9])

##### Example #2

In [58]:
arr = np.arange(1, 10)
arr[::2]

array([1, 3, 5, 7, 9])

Fetch even numbers:

In [59]:
arr[1::2]

array([2, 4, 6, 8])

Fetch odd numbers:

In [60]:
arr[::2]

array([1, 3, 5, 7, 9])

### 6.3 Masking (Fancy indexing)

#### Boolean Masking

In [61]:
arr = np.array([0, 1, 2, 3])  # Target array.
arr

array([0, 1, 2, 3])

In [62]:
mask = [True, False, True, False]  # Mask array.
arr[mask]  # arr[[True, False, True, False]]

array([0, 2])

#### Conditional filtering

In [63]:
arr = np.array([-5, 9, 20, 25, -3, 5, 16, 10, -8])
arr

array([-5,  9, 20, 25, -3,  5, 16, 10, -8])

In [64]:
arr[arr > 15]

array([20, 25, 16])

#### Usecase

Find all scores that have scored distinction and first-class.  
Find the ratio of number of students who got distinction to the number of students who got first division

In [65]:
scores_arr = np.array([20, 35, 68, 82, 83, 70, 90])
scores_arr

array([20, 35, 68, 82, 83, 70, 90])

In [66]:
distinction = scores_arr[scores_arr >= 80]
first_class = scores_arr[(scores_arr >= 60) & (scores_arr < 80)]

display(distinction, first_class)

array([82, 83, 90])

array([68, 70])

In [67]:
distinction_count = len(distinction)
first_class_count = len(first_class)

ratio = distinction_count / first_class_count

round(ratio, 2)

1.5

## 7 Update elements

> **Note**
>
> Indexing is covered much more elaborately in next notebook: `2_advance.ipynb`.

### 7.1 Using Index

##### Examples

In [68]:
arr = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 0, 8],
    ]
)

print("Before update:")
arr

Before update:


array([[1, 2, 3, 4],
       [5, 6, 0, 8]])

In [69]:
arr[1, 2] = 7

print("After update:")
arr

After update:


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 7.2 Using Slicing

##### Examples

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr[::2] = range(10, 50, 10)
print(arr)

[10  2 20  4 30  6 40  8]


In [71]:
arr = np.arange(5)
arr[2:4] = 0
arr

array([0, 1, 0, 0, 4])

In [72]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr[4:] = 10
arr

array([ 0,  1,  2,  3, 10, 10])

In [73]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.array([8, 7, 6])

print(f"Array 1:", arr_1)
print(f"Array 2:", arr_2)

print(f"{arr_1[3:]} in Array 1 will be updated with {arr_2[::-2]} from Array 2")
arr_1[3:] = arr_2[::-2]

arr_1

Array 1: [1 2 3 4 5]
Array 2: [8 7 6]
[4 5] in Array 1 will be updated with [6 8] from Array 2


array([1, 2, 3, 6, 8])

In [74]:
try:
    arr_1 = np.array([1, 2, 3, 4, 5])
    arr_2 = np.array([0, 9, 8, 7, 6])

    print(f"Array 1:", arr_1)
    print(f"Array 2:", arr_2)

    print(f"{arr_1[3:]} in Array 1 will be updated with {arr_2[::-2]} from Array 2")

    arr_1[3:] = arr_2[::-2]

except ValueError as err:
    print("Error:", err)

Array 1: [1 2 3 4 5]
Array 2: [0 9 8 7 6]
[4 5] in Array 1 will be updated with [6 8 0] from Array 2
Error: could not broadcast input array from shape (3,) into shape (2,)


> **Note**:
> 1. Broadcasting requires 

### 7.3 Using Masking

##### Examples

In [75]:
arr = np.array([-5, 9, 20, 25, -3, 5, 16, 10, -8])
print("Before Update:")
arr

Before Update:


array([-5,  9, 20, 25, -3,  5, 16, 10, -8])

In [76]:
mask = (arr >= -5) & (arr <= 15)
arr[mask] *= -1

print("After Update:")
arr

After Update:


array([  5,  -9,  20,  25,   3,  -5,  16, -10,  -8])

## 8 Import

NumPy can read data from text or csv files. [Documentation][1]

[1]: https://numpy.org/doc/2.1/user/how-to-io.html

## 9 Project

Lets solve a small use case using NumPy

### 9.1 Problem Statement

#### Net Promoter Score (NPS)

1. Net Promoter Score (NPS) is a metric used to gauge customer loyalty and satisfaction. 
1. It measures the likelihood of customers recommending a company, product, or service to others. 
1. The score is derived from a single survey question asking respondents to rate their likelihood of recommending on a scale of 0 to 10.

Compute NPS for [this dataset][1] from Kaggle.

[1]: https://www.kaggle.com/datasets/charlottetu/npsbank

### 9.2 Solution

When the rating is on scale 0 to 10,
```
NPS Formula = (% of Promoters) - (% of Detractors)
```
Where,
```
Promoters  := Score > 8  and Score <= 10
Detractors := Score >= 1 and Score < 7
```

### 9.3 Implementation

In [77]:
import os

In [78]:
input_file_path = os.path.join("data", "NPStimeseries.csv")
print("Importing CSV file from path:", input_file_path)

Importing CSV file from path: data\NPStimeseries.csv


In [79]:
# fname = Input file's relative path.
# delimiter = Columns are separated by coma.
# skiprows = Skip first row containing header text.
# usecols = Use only 6th column containing NPS information.
ratings = np.loadtxt(fname=input_file_path, delimiter=",", skiprows=1, usecols=6)
print(f"There are {ratings.size} ratings in CSV file.")

There are 5000 ratings in CSV file.


> **Note**:  
> `np.size` is same as total number of rows when the NumPy array is a Vector.

In [80]:
total_count = ratings.size
promoters = ratings[ratings > 8]
detractors = ratings[ratings < 7]

pro_per = promoters.size / total_count * 100
det_per = detractors.size / total_count * 100

nps = pro_per - det_per
print("NPS:", round(nps, 2))

NPS: 11.8
