![Numpy logo](images/numpy.png)

# NumPy Tutorials - PART 2: Advance

## 1 Setup

### 1.1 Install library

Run below command if NumPy is not already installed.
```cmd
pip install numpy
```
or
```cmd
pip3 install numpy
```

### 1.2 Import Library

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.1


### Preface

1. `len()` always returns the total number of elements in first dimension.
2. NumPy functions can be applied as global functions: `np.function_name(my_array)` or as object methods `my_array.function_name()`.
3. Using `?` after function name without invoking it using paranthesis `()`, like `my_array.function_name?` or `np.function_name?`, returns its [docstring][1].

[1]: https://peps.python.org/pep-0257/#what-is-a-docstring

## 2 Routines

### 2.1 Types of Routines

Ref: https://numpy.org/doc/stable/reference/routines.array-manipulation.html#

### 2.2 Manipulation routines

#### Reshape

Create an array of size $1 \times 13$

In [2]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
arr.shape

(12,)

In [4]:
np.reshape(arr, (3, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Reshape does not alter the original array. Original array is not modified as seen below.

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

##### Reshape cannot loose data

In [7]:
try:
    np.arange(1, 14).reshape(3, 4)

except ValueError as err:
    print("ValueError:", err)

ValueError: cannot reshape array of size 13 into shape (3,4)


##### Auto reshape using `-1`

In [8]:
arr.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr.reshape(-1, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr.reshape(-1, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [11]:
arr.reshape(12, -1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [12]:
try:
    arr.reshape(-1, -1)

except ValueError as err:
    print("Error:", err)

Error: can only specify one unknown dimension


#### Transpose

In [13]:
# Create an array of length 12 containing elements from 1 to 12 and
# rearrange those elements to form a 3-rows X 4-columns matrix.
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print("\nShape:", arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)


##### Using `T` attribute

In [14]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

original array is not modified.

In [15]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

##### Using `transpose` function

In [16]:
arr.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [17]:
np.transpose(arr)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

original array is not modified.

In [18]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Flatten

##### Flatten 1D Array

In [19]:
np.arange(10).flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Flatten 2D Array

In [20]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

##### Flatten 3D Array

In [22]:
arr = np.arange(12).reshape(2, 3, 2)

display(arr)
print("Dimension:", arr.ndim)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

Dimension: 3


In [23]:
np.arange(10).flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3 Indexing

NumPy array can be indexed in three ways:

1. Explicit indexing: By passing separate list of row indexes and column indexes.
2. Slicing: Using colon `:` operator.
3. Fancy indexing or Masking: Using comparison operators (`<`, `>`, `==`, `>=`, `<=`, `!=`) on NumPy array.

### 2.1 Dimensional Indexing

#### Case #1: Accessing single element

Create an array of size $3 \times 4$

In [24]:
# Reshape array of length 12 to 3X4 matrix.
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Different ways to access elements in 2D array. For example to access second row third element:

1. Second row index: 1
2. Third column index: 2

In [25]:
arr[1][2]

np.int64(7)

In [26]:
arr[1, 2]

np.int64(7)

#### Case #2: Accessing multiple elements

Create an array of size $4 \times 4$

In [27]:
# Reshape array of length 16 to 4X4 matrix.
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Syntax

```
arr[
    [list of row indices],
    [list of column indices],
]
```

##### Examples

In [28]:
arr[[1, 2]]  # List of column indices are optional.

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr[
    [1, 2, -1],
    [1, 0, -1],
]

array([ 6,  9, 16])

### 2.2 Slicing

Create an array of size $4 \times 4$

In [30]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

```
arr[row_index_start:row_index_end, column_index_start:column_index_end]
```

1. Default value for `row_index_start` is zero.
2. Default value for `column_index_start` is zero.
3. `row_index_end` is exclusive.
4. `column_index_end` is exclusive.

#### Row Slicing

##### Case #1: Default indexes

In [31]:
arr[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Case #2: Index within range

In [32]:
arr[0:4]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Case #3: Index out of range

When only `row_index_start` is out of range:

In [33]:
arr[4:]

array([], shape=(0, 4), dtype=int64)

When only `row_index_end` is out of range:

In [34]:
arr[:5]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Case #4: Negative indexes

In [35]:
arr[1:-2]

array([[5, 6, 7, 8]])

#### Column Slicing

##### Case #1: Default Indexes

In [36]:
arr[:, :]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Case #2: Indexes within range

In [37]:
arr[:, 0:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

`column_index_end` is exclusive.

In [38]:
arr[:, 0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

##### Case #3: Indexes out of range

In [39]:
arr[:, :5]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
np.arange(1, 15)[[0, -1, 2]]

array([ 1, 14,  3])

##### Case #4: Negative indexes

In [41]:
arr[:, -1:]

array([[ 4],
       [ 8],
       [12],
       [16]])

In [42]:
arr[:, -1:2]

array([], shape=(4, 0), dtype=int64)

### 2.3 Fancy indexing / Masking

Create an array of size $4 \times 4$

In [43]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### Masking using single conditions

In [44]:
arr < 8

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

#### Masking using multi conditions

Multiple conditions can be applied using logical bitwise operators grouped in parentheses:
1. `&`: AND
2. `|`: OR
3. `~`: NOT
4. `^`: XOR
5. `>>`: Right Shift
6. `<<`: Left Shift

For example below mask has multiple conditions inside parentheses separated by `&` operator.

In [45]:
(arr > 7) & (arr < 14)

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

#### Fetch data using Masking

In [46]:
mask = (arr > 7) & (arr < 14)
arr[mask]  # Apply mask on array

array([ 8,  9, 10, 11, 12, 13])

> **Note**:
>
> Fetching data (or filtering) using Masking always returns single dimensional array.

## 3 Axis

Before utilizing on different types of functions in NumPy, its important to understand the concept of **axis** w.r.t NumPy arrays.

##### TL;DR

The dimension array:

* 1st Dimension: [Row, ]
* 2nd Dimension: [Columns, Rows]
* 3rd Dimension: [Layers, Columns, Rows]
* 4th Dimension: [Batch, Layers, Columns, Rows]

**Axis represents the index of dimension in the dimension array**

### Axis in 1D Array

In [47]:
arr = np.array([0, 1, 2, 3])
arr.shape

(4,)

#### No Axis

In [48]:
np.sum(arr)

np.int64(6)

#### Axis Zero

In [49]:
np.sum(arr, axis=0)

np.int64(6)

#### Axis One

In [50]:
try:
    np.sum(arr, axis=1)

except np.exceptions.AxisError as err:
    print(err)

axis 1 is out of bounds for array of dimension 1


### Axis in 2D Array

In [51]:
arr = np.arange(1, 7).reshape(2, 3)

display(arr)
print("\nShape:", arr.shape)

array([[1, 2, 3],
       [4, 5, 6]])


Shape: (2, 3)


* Shape: (2, 3) → 2 rows, 3 columns
* Axis 0 → rows (vertical direction)
* Axis 1 → columns (horizontal direction)

#### No Axis

In [52]:
np.sum(arr)

np.int64(21)

#### Axis Zero

In [53]:
np.sum(arr, axis=0)

array([5, 7, 9])

#### Axis One

In [54]:
np.sum(arr, axis=1)

array([ 6, 15])

#### Axis Two

In [55]:
try:
    np.sum(arr, axis=2)

except np.exceptions.AxisError as err:
    print(err)

axis 2 is out of bounds for array of dimension 2


### Axis in 3D Array

In [56]:
arr = np.arange(1, 13).reshape(2, 2, 3)
print(arr)
print("\nShape:", arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Shape: (2, 2, 3)


#### No Axis

In [57]:
np.sum(arr)

np.int64(78)

#### Axis Zero

In [58]:
np.sum(arr, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

#### Axis One

In [59]:
np.sum(arr, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

#### Axis Two

In [60]:
np.sum(arr, axis=2)

array([[ 6, 15],
       [24, 33]])

#### Axis Three

In [61]:
try:
    np.sum(arr, axis=3)

except np.exceptions.AxisError as err:
    print(err)

axis 3 is out of bounds for array of dimension 3


## 4 Vectorization

In [62]:
def random_operation(val: int) -> int:
    if val % 2 == 0:
        val += 1
    else:
        val -= 1

    return val

In [63]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
try:
    random_operation(arr)

except ValueError as err:
    print("ValueError:", err)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [65]:
vec_random_operation = np.vectorize(random_operation)

In [66]:
type(vec_random_operation)

numpy.vectorize

In [67]:
vec_random_operation(arr)

array([1, 0, 3, 2, 5, 4, 7, 6, 9, 8])

## 5 Broadcasting

### 5.1 What is Broadcasting?

https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcasting

![NumPy Broadcasting](images/numpy_broadcasting.png)

Image source: https://mathematica.stackexchange.com/q/99171/110892

In [68]:
def display_ndarray(name, array):
    """
    Function to display NumPy array.
    """
    print(f"\nArray {name}:")
    print(array)
    print("Shape:", array.shape)

In [69]:
a = np.array(
    [
        [0],
        [10],
        [20],
        [30],
    ]
)
display_ndarray("A", a)

b = np.array([0, 1, 2])
display_ndarray("B", b)

display_ndarray("A + B", a + b)


Array A:
[[ 0]
 [10]
 [20]
 [30]]
Shape: (4, 1)

Array B:
[0 1 2]
Shape: (3,)

Array A + B:
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
Shape: (4, 3)


### 5.2 Rules for Broadcasting

1. If two arrays differ in the number of dimensions, the shape of array with fewer dimensions is padded with ones on its leading left side.
2. If the shape of two arrays does not match in any dimensions, the array with shape equal to 1 is stretched to match the other shape.

### 5.3 Example

#### Problem statement

Given two arrays A and B,

1. Shape of Array A: `(8, 1, 6, 1)`
2. Shape of Array B: `   (7, 1, 5)`

Applying Broadcasting rules on A and B:

#### Solution

##### Applying Rule #1:

Since shape of array B has fewer dimension compared to array A, new dimension is added to array B on the left most side:

After applying Broadcasting rule #1 on A and B:

1. Unchanged shape of Array A: `(8, 1, 6, 1)`
2. New shape of Array B after padding: `(1, 7, 1, 5)`

##### Applying Rule #2:

After applying rule #1, since the shape of both arrays does not match in any dimension, both arrays are stretched wherever their dimension is One.

After applying Broadcasting rule #2 on A and B:

1. New shape of Array A: `(8, 7, 6, 5)`
2. New shape of Array B: `(8, 7, 6, 5)`