![Numpy logo](images/numpy.png)

# NumPy Tutorials - PART 2: Functions

## 1 Setup

### 1.1 Import Library

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.1


## 2 Shallow vs Deep Copy

### 2.1 Python list

#### Shallow Copy in Python List

In [2]:
a = [1, 2, 3, 4]
b = a

a[1] = 100
b

[1, 100, 3, 4]

In [3]:
a is b

True

#### Deep Copy in Python List

In [4]:
a = [1, 2, 3, 4]
b = a[:]

a[1] = 100
b

[1, 2, 3, 4]

In [5]:
a is b

False

### 2.2 NumPy array

#### Shallow Copy in NumPy array

In [6]:
a = np.array([1, 2, 3, 4])
b = a.reshape(2, 2)

a[1] = 100
b

array([[  1, 100],
       [  3,   4]])

In [7]:
a is b

False

In [8]:
np.shares_memory(a, b)

True

#### Deep Copy in NumPy array

In [9]:
a = np.array([1, 2, 3, 4])
b = a + 0

a[1] = 100
b

array([1, 2, 3, 4])

In [10]:
a is b

False

In [11]:
np.shares_memory(a, b)

False

### 2.3 `np.view` vs `np.copy`

#### `np.view()`

##### Example #1

In [12]:
a = np.array([1, 2, 3, 4])
b = a.view()

a[1] = 100
b

array([  1, 100,   3,   4])

In [13]:
a is b

False

In [14]:
np.shares_memory(a, b)

True

##### Example #2

In [15]:
a = np.array([1, 2, 3, 4])
b = (a + 0).view()

a[1] = 100
b

array([1, 2, 3, 4])

In [16]:
a is b

False

In [17]:
np.shares_memory(a, b)

False

#### `np.copy()`

##### Example #1

In [18]:
a = np.array([1, 2, 3, 4])
b = a.copy()

a[1] = 100
b

array([1, 2, 3, 4])

In [19]:
a is b

False

In [20]:
np.shares_memory(a, b)

False

In [21]:
a = np.array([0, 1, 2, 3, 4, 5])
b = a[a % 1 == 0]
b[0] = 10
a[:2]

array([0, 1])

## 3 Manipulation routines

### 3.1 Spliting

#### `np.split`

##### Example #1: One dimensional array

In [22]:
arr = np.arange(0, 8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

Default value for `axis` parameter of `np.split()` is `0`.

In [23]:
np.split(arr, 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [24]:
try:
    np.split(arr, 3)

except ValueError as err:
    print("ValueError:", err)

ValueError: array split does not result in an equal division


In [25]:
splits = np.split(arr, indices_or_sections=[2, 5, 7, 8, 100])
splits

[array([0, 1]),
 array([2, 3, 4]),
 array([5, 6]),
 array([7]),
 array([], dtype=int64),
 array([], dtype=int64)]

> **Note**:
>
> `indices_or_sections` accepts values out of range

In [26]:
type(splits)

list

In [27]:
np.split(arr, 2, axis=0)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

##### Example #2: Two dimensional array

In [28]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Default value for `axis` parameter is `0`.

In [29]:
np.split(arr, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

When `axis` is explicitly set to `0`.

In [30]:
np.split(arr, 2, axis=0)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

When `axis` is explicitly set to `1`.

In [31]:
np.split(arr, 2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

#### `np.vsplit`

##### Example #1: One dimensional array

In [32]:
arr = np.arange(0, 8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
try:
    np.vsplit(arr, 2)

except ValueError as err:
    print("ValueError:", err)

ValueError: vsplit only works on arrays of 2 or more dimensions


##### Example #2: Two dimensional array

In [34]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
np.vsplit(arr, 2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

#### `np.hsplit`

##### Example #1: One dimensional array

In [36]:
arr = np.arange(0, 8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [37]:
np.hsplit(arr, 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

##### Example #2: Two dimensional array

In [38]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
np.hsplit(arr, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

### 3.2 Stacking

#### `np.concatenate`

##### Example #1: One dimensional array

In [40]:
arr1 = np.arange(0, 4)
arr1

array([0, 1, 2, 3])

In [41]:
arr2 = np.arange(5, 9)
arr2

array([5, 6, 7, 8])

Default value for `axis` parameter of `np.concatenate()` is `0`.

In [42]:
np.concatenate((arr1, arr2))

array([0, 1, 2, 3, 5, 6, 7, 8])

In [43]:
np.concatenate((arr1, arr2), axis=0)

array([0, 1, 2, 3, 5, 6, 7, 8])

In [44]:
try:
    np.concatenate((arr1, arr2), axis=1)

except np.exceptions.AxisError as err:
    print("AxisError:", err)

AxisError: axis 1 is out of bounds for array of dimension 1


##### Example #2: Two dimensional array

In [45]:
arr1 = np.arange(1, 17).reshape(4, 4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [46]:
arr2 = np.arange(1, 17).reshape(4, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Default value for `axis` parameter is `0`.

In [47]:
np.concatenate((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

When axis is explicitly set to zero.

In [48]:
np.concatenate((arr1, arr2), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

When axis is explicitly set to one.

In [49]:
np.concatenate((arr1, arr2), axis=1)

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16]])

#### `np.vstack`

##### Example #1

In [50]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

##### Example #2

In [51]:
arr = np.arange(1, 4)
arr

array([1, 2, 3])

In [52]:
op = np.vstack((arr, arr))

display(op)
print("\nShape:", op.shape)

array([[1, 2, 3],
       [1, 2, 3]])


Shape: (2, 3)


In [53]:
arr = np.arange(1, 5).reshape(2, 2)
arr

array([[1, 2],
       [3, 4]])

In [54]:
op = np.vstack((arr, arr))

display(op)
print("\nShape:", op.shape)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])


Shape: (4, 2)


#### `np.hstack`

##### Example #1

In [55]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16]])

##### Example #2

In [56]:
arr = np.arange(1, 4)
arr

array([1, 2, 3])

In [57]:
op = np.hstack((arr, arr))

display(op)
print("\nShape:", op.shape)

array([1, 2, 3, 1, 2, 3])


Shape: (6,)


In [58]:
arr = np.arange(1, 5).reshape(2, 2)
arr

array([[1, 2],
       [3, 4]])

In [59]:
op = np.hstack((arr, arr))

display(op)
print("\nShape:", op.shape)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])


Shape: (2, 4)


Horizontally stacking two vertical arrays of same shape:

In [60]:
a = np.array(
    [
        [1],
        [2],
        [3],
    ]
)
b = np.array(
    [
        [4],
        [5],
        [6],
    ]
)
np.hstack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

Horizontally stacking two vertical arrays of different shape:

In [61]:
try:
    a = np.array(
        [
            [1],
            [2],
            [3],
        ]
    )
    b = np.array(
        [
            [4],
            [5],
            [6],
            [7],
        ]
    )
    np.hstack((a, b))

except ValueError as err:
    print("ValueError:", err)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4


## 4 Matrix

### 4.1 Matrix Initialization

### 4.2 Matrix Multiplication