## 1 Setup

### 1.1 Import libraries

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.4.1


Some common aggregation functions:

1. `np.sum()`: Calculates the sum of array elements.
1. `np.mean()`: Computes the arithmetic mean (average) of array elements.
1. `np.median()`: Determines the median value of array elements.
1. `np.min()`: Finds the minimum value within the array.
1. `np.max()`: Finds the maximum value within the array.

## 3 Mathematical Functions

Ref: https://numpy.org/doc/stable/reference/routines.math.html

### `sum`

In [2]:
arr = np.arange(1, 7).reshape(2, 3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr.sum?

Signature: arr.sum(axis=None, dtype=None, out=None, **kwargs)
Docstring:
a.sum(axis=None, dtype=None, out=None, *, keepdims=<no value>, initial=<no value>, where=<no value>)

Return the sum of the array elements over the given axis.

Refer to `numpy.sum` for full documentation.

See Also
--------
numpy.sum : equivalent function
Type:      builtin_function_or_method

#### No Axis

In [4]:
arr.sum()

np.int64(21)

#### Axis Zero

In [5]:
arr.sum(axis=0)

array([5, 7, 9])

#### Axis One

In [6]:
arr.sum(axis=1)

array([ 6, 15])

### `max`

In [7]:
arr = np.array(
    [
        [1, 6, 3, 8],
        [5, 2, 7, 4],
    ]
)
arr

array([[1, 6, 3, 8],
       [5, 2, 7, 4]])

In [8]:
arr.max?

Signature: arr.max(axis=None, out=None, **kwargs)
Docstring:
a.max(axis=None, out=None, *, keepdims=<no value>, initial=<no value>, where=<no value>)

Return the maximum along a given axis.

Refer to `numpy.amax` for full documentation.

See Also
--------
numpy.amax : equivalent function
Type:      builtin_function_or_method

#### No Axis

In [9]:
arr.max()

np.int64(8)

#### Axis Zero

In [10]:
arr.max(axis=0)

array([5, 6, 7, 8])

#### Axis One

In [11]:
arr.max(axis=1)

array([8, 7])

In [12]:
np.cumsum([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

## 4 Logical Functions

https://numpy.org/doc/stable/reference/routines.logic.html

### Truth value testing

https://numpy.org/doc/stable/reference/routines.logic.html#truth-value-testing

#### `any`

In [13]:
ages = np.array([32, 16, 18, 24, 50])
ages

array([32, 16, 18, 24, 50])

##### `any` on filters

###### Option #1

In [14]:
ages > 18

array([ True, False, False,  True,  True])

In [15]:
np.any(ages > 18)

np.True_

###### Option #2

In [16]:
(ages < 12)

array([False, False, False, False, False])

In [17]:
(ages < 12).any()

np.False_

In [18]:
(ages > 12)

array([ True,  True,  True,  True,  True])

In [19]:
(ages > 12).any()

np.True_

##### `any` on Arrays

###### Case #1: Negative, Zero and Positive numbers

In [20]:
arr = np.array([-1, 0, 1, 2])
arr

array([-1,  0,  1,  2])

In [21]:
arr.any()

np.True_

###### Case #2: Zero and Negative numbers

In [22]:
arr = np.array([-2, -1, 0])
arr

array([-2, -1,  0])

In [23]:
arr.any()

np.True_

###### Case #3: Only Zeros

In [24]:
arr = np.array([0, 0, 0])
arr

array([0, 0, 0])

In [25]:
arr.any()

np.False_

#### `all`

In [26]:
ages = np.array([32, 16, 18, 24, 50])
ages

array([32, 16, 18, 24, 50])

##### `all` on filters

###### Option #1

In [27]:
ages > 18

array([ True, False, False,  True,  True])

In [28]:
np.all(ages > 18)

np.False_

###### Option #2

In [29]:
(ages > 12)

array([ True,  True,  True,  True,  True])

In [30]:
(ages > 12).all()

np.True_

In [31]:
(ages < 12)

array([False, False, False, False, False])

In [32]:
(ages < 12).all()

np.False_

##### `all` on Arrays

###### Case #1: Negative, Zero and Positive numbers

In [33]:
arr = np.array([-1, 0, 1, 2])
arr

array([-1,  0,  1,  2])

In [34]:
arr.all()

np.False_

###### Case #2: Zero and Negative numbers

In [35]:
arr = np.array([-2, -1, 0])
arr

array([-2, -1,  0])

In [36]:
arr.all()

np.False_

###### Case #3: Only Zeros

In [37]:
arr = np.array([0, 0, 0])
arr

array([0, 0, 0])

In [38]:
arr.all()

np.False_

## 5 Aggregation Functions

https://numpy.org/doc/stable/reference/routines.sort.html

### 5.1 `where`

#### `where` on 1D Array

In [39]:
arr = np.array([6, -2, 0, 8, 5, 0, 10])
arr

array([ 6, -2,  0,  8,  5,  0, 10])

In [40]:
np.where(arr < 5, 0, 1)

array([1, 0, 0, 1, 1, 0, 1])

In [41]:
np.where(arr < 5)

(array([1, 2, 5]),)

In [42]:
np.where(arr)

(array([0, 1, 3, 4, 6]),)

#### `where` on 2D Array

In [43]:
arr = np.arange(1, 17).reshape(4, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [44]:
np.where(arr < 9, 0, 1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [45]:
arr = np.array(
    [
        [0, 1, 2],
        [3, 0, 4],
        [5, 6, 0],
    ]
)

In [46]:
np.where(arr)

(array([0, 0, 1, 1, 2, 2]), array([1, 2, 0, 2, 0, 1]))

## 6 Sorting

In [47]:
arr = np.array([10, 6, 0, 5, 7, 1])
arr

array([10,  6,  0,  5,  7,  1])

In [48]:
arr.sort()
arr

array([ 0,  1,  5,  6,  7, 10])

> **Note**:
>
> NumPy uses Tim sort algorithm to sort elements in the array

#### Axis in Sorting

> **Note**:
>
> Default value for axis in `np.sort` is -1, hence NumPy always sorts array by last dimension by default

### 6.1 Sorting on 1D Array

In [49]:
arr = np.array([16, 2, 13, 9])
arr

array([16,  2, 13,  9])

##### No Axis

In [50]:
np.sort(arr)

array([ 2,  9, 13, 16])

##### Axis Zero

In [51]:
np.sort(arr, axis=0)

array([ 2,  9, 13, 16])

##### Axis One

In [52]:
try:
    np.sort(arr, axis=1)

except np.exceptions.AxisError as err:
    print("AxisError:", err)

AxisError: axis 1 is out of bounds for array of dimension 1


### 6.2 Sorting 2D Array

In [53]:
arr = np.array(
    [
        [16, 2, 13, 9],
        [1, 6, 17, 18],
        [4, 10, 7, 11],
        [13, 18, 5, 6],
    ]
)
arr

array([[16,  2, 13,  9],
       [ 1,  6, 17, 18],
       [ 4, 10,  7, 11],
       [13, 18,  5,  6]])

##### No Axis

In [54]:
np.sort(arr)

array([[ 2,  9, 13, 16],
       [ 1,  6, 17, 18],
       [ 4,  7, 10, 11],
       [ 5,  6, 13, 18]])

##### Axis Zero

In [55]:
np.sort(arr, axis=0)

array([[ 1,  2,  5,  6],
       [ 4,  6,  7,  9],
       [13, 10, 13, 11],
       [16, 18, 17, 18]])

##### Axis One

In [56]:
np.sort(arr, axis=1)

array([[ 2,  9, 13, 16],
       [ 1,  6, 17, 18],
       [ 4,  7, 10, 11],
       [ 5,  6, 13, 18]])

### 6.3 Sorting 3D Array

In [57]:
arr = np.array(
    [
        [
            [16, 2, 9],
            [1, 6, 18],
            [4, 7, 11],
            [3, 18, 5],
        ],
        [
            [1, 4, 13],
            [6, 2, 10],
            [13, 5, 7],
            [6, 11, 9],
        ],
    ]
)
print(arr)
print("\nShape:", arr.shape)

[[[16  2  9]
  [ 1  6 18]
  [ 4  7 11]
  [ 3 18  5]]

 [[ 1  4 13]
  [ 6  2 10]
  [13  5  7]
  [ 6 11  9]]]

Shape: (2, 4, 3)


##### No Axis

In [58]:
np.sort(arr)

array([[[ 2,  9, 16],
        [ 1,  6, 18],
        [ 4,  7, 11],
        [ 3,  5, 18]],

       [[ 1,  4, 13],
        [ 2,  6, 10],
        [ 5,  7, 13],
        [ 6,  9, 11]]])

##### Axis Zero

In [59]:
np.sort(arr, axis=0)

array([[[ 1,  2,  9],
        [ 1,  2, 10],
        [ 4,  5,  7],
        [ 3, 11,  5]],

       [[16,  4, 13],
        [ 6,  6, 18],
        [13,  7, 11],
        [ 6, 18,  9]]])

##### Axis One

In [60]:
np.sort(arr, axis=1)

array([[[ 1,  2,  5],
        [ 3,  6,  9],
        [ 4,  7, 11],
        [16, 18, 18]],

       [[ 1,  2,  7],
        [ 6,  4,  9],
        [ 6,  5, 10],
        [13, 11, 13]]])

##### Axis Two

In [61]:
np.sort(arr, axis=2)

array([[[ 2,  9, 16],
        [ 1,  6, 18],
        [ 4,  7, 11],
        [ 3,  5, 18]],

       [[ 1,  4, 13],
        [ 2,  6, 10],
        [ 5,  7, 13],
        [ 6,  9, 11]]])

##### Axis Three

In [62]:
try:
    np.sort(arr, axis=3)

except np.exceptions.AxisError as err:
    print(err)

axis 3 is out of bounds for array of dimension 3


## 7 Random Sampling

### `rand`

In [63]:
np.random.rand(5)

array([0.79110192, 0.57020723, 0.42690153, 0.26326897, 0.17353403])

In [64]:
arr = np.random.rand(2, 4, 3)

display(arr)
arr.shape

array([[[0.24007784, 0.62750977, 0.29694523],
        [0.38091494, 0.35707216, 0.48189784],
        [0.05360059, 0.41463123, 0.7565146 ],
        [0.11152114, 0.79030614, 0.01549754]],

       [[0.62919853, 0.87261377, 0.9828398 ],
        [0.35926883, 0.62980417, 0.69402057],
        [0.53253655, 0.58982102, 0.78638997],
        [0.69048519, 0.03017303, 0.00848715]]])

(2, 4, 3)

### `randn`

In [65]:
np.random.randn(5)

array([ 1.33603903, -1.49910117,  0.62268225,  0.1664038 ,  0.34478073])

In [66]:
arr = np.random.randn(2, 4, 3)

display(arr)
arr.shape

array([[[ 1.95537467,  0.49291214, -0.69201466],
        [-0.62811149,  1.33261404,  0.28204831],
        [ 0.01104906, -0.48539574, -0.49916294],
        [-2.16400917, -0.9446618 ,  0.9089128 ]],

       [[ 0.56786645,  0.62868637, -0.39891944],
        [ 1.16778621,  0.47288732,  1.82622099],
        [-0.33598468, -0.54679276,  0.47855889],
        [-1.18563822,  1.98097737, -1.3976794 ]]])

(2, 4, 3)

### `randint`

In [67]:
np.random.randint(low=0, high=256, size=5, dtype="uint8")

array([ 85, 104,   8,  90,  66], dtype=uint8)

In [68]:
arr = np.random.randint(2, size=(2, 4, 3))

display(arr)
arr.shape

array([[[0, 0, 1],
        [1, 0, 0],
        [0, 0, 0],
        [1, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 0],
        [0, 1, 1]]], dtype=int32)

(2, 4, 3)

### `random`

In [69]:
np.random.random(5)

array([0.81134103, 0.29496576, 0.76468687, 0.71197032, 0.3629201 ])

In [70]:
arr = np.random.random(size=(3, 2, 4))

display(arr)
arr.shape

array([[[0.85221834, 0.004441  , 0.53994551, 0.17626665],
        [0.08071282, 0.44453552, 0.86716812, 0.2387718 ]],

       [[0.8630452 , 0.08678617, 0.88028793, 0.49102759],
        [0.5148849 , 0.1398266 , 0.20968263, 0.91615005]],

       [[0.81054622, 0.41094506, 0.74558545, 0.03287117],
        [0.29852531, 0.87130709, 0.43777166, 0.07184663]]])

(3, 2, 4)

### `choice`

In [71]:
np.random.choice(a=["Red", "Red", "Red", "Green", "Green"], size=3, replace=True)

array(['Red', 'Red', 'Red'], dtype='<U5')

In [72]:
# By default `replace` is set to True.
np.random.choice(a=["Red", "Red", "Red", "Green", "Green"], size=4, replace=False)

array(['Red', 'Red', 'Green', 'Red'], dtype='<U5')